name: Daily redeem

on:
  schedule:
    - cron: '0 4 * * *' # UTC hour

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      MIGHTPULSE_API_KEY: ${{ secrets.MIGHTPULSE_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: |
          npm ci
          node ks-redeemer.js --alliances=FRA,emr --kid=2363 --ignored-codes=VIP777,Kingshot888
