name: Manual redeem

on:
  workflow_dispatch:
    inputs:
      ignoredCodes:
        description: 'Codes to ignore'
        required: false
        default: 'Kingshot888,VIP777'
      withCodes:
        description: 'Codes to redeem (will replace codes fetched from API)'
        required: false
      alliances:
        description: 'Alliances to redeem for'
        required: false
        default: 'FRA,emr'
      kingdomId:
        description: 'Kingdom ID of the alliances'
        required: false
        default: '2363'

jobs:
  run:
    runs-on: ubuntu-latest

    env:
      MIGHTPULSE_API_KEY: ${{ secrets.MIGHTPULSE_API_KEY }}

    steps:
      - uses: actions/checkout@v4

      - uses: actions/setup-node@v4
        with:
          node-version: 24

      - run: |
          npm ci
          node ks-redeemer.js --alliances=${{ github.event.inputs.alliances }} --kid=${{ github.event.inputs.kingdomId }} --ignored-codes=${{ github.event.inputs.ignoredCodes }} --codes=${{ github.event.inputs.withCodes }}
